wagtailmedia/models.py
from __future__ import unicode_literals

import mimetypes
import os.path

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.core.validators import MinValueValidator
from django.db import models
from django.dispatch import Signal
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from wagtail import VERSION as WAGTAIL_VERSION
from wagtail.core.models import CollectionMember
from wagtail.search import index
from wagtail.search.queryset import SearchableQuerySetMixin

from taggit.managers import TaggableManager


if WAGTAIL_VERSION < (2, 9):
    from wagtail.admin.utils import get_object_usage
else:
    from wagtail.admin.models import get_object_usage


class MediaQuerySet(SearchableQuerySetMixin, models.QuerySet):
    pass


class AbstractMedia(CollectionMember, index.Indexed, models.Model):
    MEDIA_TYPES = (
        ("audio", _("Audio file")),
        ("video", _("Video file")),
    )

    title = models.CharField(max_length=255, verbose_name=_("title"))
    file = models.FileField(upload_to="media", verbose_name=_("file"))

    type = models.CharField(
        choices=MEDIA_TYPES, max_length=255, blank=False, null=False
    )
    duration = models.FloatField(
        blank=True,
        default=0,
        validators=[MinValueValidator(0)],
        verbose_name=_("duration"),
        help_text=_("Duration in seconds"),
    )
    width = models.PositiveIntegerField(null=True, blank=True, verbose_name=_("width"))
    height = models.PositiveIntegerField(
        null=True, blank=True, verbose_name=_("height")
    )
    thumbnail = models.FileField(
        upload_to="media_thumbnails", blank=True, verbose_name=_("thumbnail")
    )

    created_at = models.DateTimeField(verbose_name=_("created at"), auto_now_add=True)
    uploaded_by_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("uploaded by user"),
        null=True,
        blank=True,
        editable=False,
        on_delete=models.SET_NULL,
    )

    tags = TaggableManager(help_text=None, blank=True, verbose_name=_("tags"))

    objects = MediaQuerySet.as_manager()

    search_fields = CollectionMember.search_fields + [
        index.SearchField("title", partial_match=True, boost=10),
        index.RelatedFields(
            "tags",
            [
                index.SearchField("name", partial_match=True, boost=10),
            ],
        ),
        index.FilterField("uploaded_by_user"),
    ]

    def __str__(self):
        return self.title

    @property
    def filename(self):
        return os.path.basename(self.file.name)

    @property
    def thumbnail_filename(self):
        return os.path.basename(self.thumbnail.name)

    @property
    def file_extension(self):
        return os.path.splitext(self.filename)[1][1:]

    @property
    def url(self):
        return self.file.url

    @property
    def sources(self):
        return [
            {
                "src": self.url,
                "type": mimetypes.guess_type(self.filename)[0]
                or "application/octet-stream",
            }
        ]

    def get_usage(self):
        return get_object_usage(self)

    @property
    def usage_url(self):
        return reverse("wagtailmedia:media_usage", args=(self.id,))

    def is_editable_by_user(self, user):
        from wagtailmedia.permissions import permission_policy

        return permission_policy.user_has_permission_for_instance(user, "change", self)

    def clean(self, *args, **kwargs):
        super().clean(*args, **kwargs)
        if not self.duration:
            self.duration = 0

    class Meta:
        abstract = True
        verbose_name = _("media")


class Media(AbstractMedia):
    admin_form_fields = (
        "title",
        "file",
        "collection",
        "duration",
        "width",
        "height",
        "thumbnail",
        "tags",
    )


def get_media_model():
    from django.apps import apps
    from django.conf import settings

    try:
        app_label, model_name = settings.WAGTAILMEDIA_MEDIA_MODEL.split(".")
    except AttributeError:
        return Media
    except ValueError:
        raise ImproperlyConfigured(
            "WAGTAILMEDIA_MEDIA_MODEL must be of the form 'app_label.model_name'"
        )

    media_model = apps.get_model(app_label, model_name)
    if media_model is None:
        raise ImproperlyConfigured(
            "WAGTAILMEDIA_MEDIA_MODEL refers to model '%s' that has not been installed"
            % settings.WAGTAILMEDIA_MEDIA_MODEL
        )
    return media_model


# Provides `request` as an argument
media_served = Signal()

wagtailmedia/forms.py
from __future__ import unicode_literals

from django import forms
from django.conf import settings
from django.forms.models import modelform_factory
from django.utils.module_loading import import_string
from django.utils.translation import gettext_lazy as _

from wagtail import VERSION as WAGTAIL_VERSION
from wagtail.admin import widgets

from wagtailmedia.models import Media
from wagtailmedia.permissions import permission_policy as media_permission_policy


if WAGTAIL_VERSION < (2, 5):
    from wagtail.admin.forms import (
        BaseCollectionMemberForm,
        collection_member_permission_formset_factory,
    )
else:
    from wagtail.admin.forms.collections import (
        BaseCollectionMemberForm,
        collection_member_permission_formset_factory,
    )


class BaseMediaForm(BaseCollectionMemberForm):
    class Meta:
        widgets = {
            "tags": widgets.AdminTagWidget,
            "file": forms.FileInput,
            "thumbnail": forms.ClearableFileInput,
        }

    permission_policy = media_permission_policy

    def __init__(self, *args, **kwargs):
        super(BaseMediaForm, self).__init__(*args, **kwargs)

        if self.instance.type == "audio":
            for name in ("width", "height"):
                # these fields might be editable=False so verify before accessing
                if name in self.fields:
                    del self.fields[name]


def get_media_base_form():
    base_form_override = getattr(settings, "WAGTAILMEDIA_MEDIA_FORM_BASE", "")
    if base_form_override:
        base_form = import_string(base_form_override)
    else:
        base_form = BaseMediaForm
    return base_form


media_base_form = get_media_base_form()


def get_media_form(model):
    fields = model.admin_form_fields
    if "collection" not in fields:
        # force addition of the 'collection' field, because leaving it out can
        # cause dubious results when multiple collections exist (e.g adding the
        # media to the root collection where the user may not have permission) -
        # and when only one collection exists, it will get hidden anyway.
        fields = list(fields) + ["collection"]

    return modelform_factory(
        model,
        form=media_base_form,
        fields=fields,
    )


GroupMediaPermissionFormSet = collection_member_permission_formset_factory(
    Media,
    [
        ("add_media", _("Add"), _("Add/edit media you own")),
        ("change_media", _("Edit"), _("Edit any media")),
    ],
    "wagtailmedia/permissions/includes/media_permissions_formset.html",
)

wagtailmedia/__init__.py
__version__ = "0.7.1"

default_app_config = "wagtailmedia.apps.WagtailMediaAppConfig"

wagtailmedia/views/chooser.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from wagtail import VERSION as WAGTAIL_VERSION
from wagtail.admin.modal_workflow import render_modal_workflow
from wagtail.core import hooks
from wagtail.core.models import Collection
from wagtail.search.backends import get_search_backends

from wagtailmedia.forms import get_media_form
from wagtailmedia.models import get_media_model
from wagtailmedia.permissions import permission_policy
from wagtailmedia.utils import paginate


if WAGTAIL_VERSION < (2, 5):
    from wagtail.admin.forms import SearchForm

    pagination_template = "wagtailadmin/shared/pagination_nav.html"
else:
    from wagtail.admin.forms.search import SearchForm

    pagination_template = "wagtailadmin/shared/ajax_pagination_nav.html"

if WAGTAIL_VERSION < (2, 9):
    from wagtail.admin.utils import PermissionPolicyChecker
else:
    from wagtail.admin.auth import PermissionPolicyChecker

permission_checker = PermissionPolicyChecker(permission_policy)


def get_media_json(media):
    """
    helper function: given a media, return the json to pass back to the
    chooser panel
    """

    return {
        "id": media.id,
        "title": media.title,
        "edit_link": reverse("wagtailmedia:edit", args=(media.id,)),
    }


def chooser(request):
    media_files = permission_policy.instances_user_has_any_permission_for(
        request.user, ["change", "delete"]
    )

    # allow hooks to modify the queryset
    for hook in hooks.get_hooks("construct_media_chooser_queryset"):
        media_files = hook(media_files, request)

    if permission_policy.user_has_permission(request.user, "add"):
        Media = get_media_model()
        MediaForm = get_media_form(Media)
        uploadform = MediaForm(user=request.user, prefix="media-chooser-upload")
    else:
        uploadform = None

    q = None
    is_searching = False
    if "q" in request.GET or "p" in request.GET or "collection_id" in request.GET:
        collection_id = request.GET.get("collection_id")
        if collection_id:
            media_files = media_files.filter(collection=collection_id)

        searchform = SearchForm(request.GET)
        if searchform.is_valid():
            q = searchform.cleaned_data["q"]

            media_files = media_files.search(q)
            is_searching = True
        else:
            media_files = media_files.order_by("-created_at")
            is_searching = False

        # Pagination
        paginator, media_files = paginate(request, media_files, per_page=10)

        return render(
            request,
            "wagtailmedia/chooser/results.html",
            {
                "media_files": media_files,
                "query_string": q,
                "is_searching": is_searching,
                "pagination_template": pagination_template,
            },
        )
    else:
        searchform = SearchForm()

        collections = Collection.objects.all()
        if len(collections) < 2:
            collections = None

        media_files = media_files.order_by("-created_at")
        paginator, media_files = paginate(request, media_files, per_page=10)

    return render_modal_workflow(
        request,
        "wagtailmedia/chooser/chooser.html",
        None,
        {
            "media_files": media_files,
            "searchform": searchform,
            "collections": collections,
            "uploadform": uploadform,
            "is_searching": False,
            "pagination_template": pagination_template,
        },
        json_data={
            "step": "chooser",
            "error_label": "Server Error",
            "error_message": "Report this error to your webmaster with the following information:",
            "tag_autocomplete_url": reverse("wagtailadmin_tag_autocomplete"),
        },
    )


def media_chosen(request, media_id):
    media = get_object_or_404(get_media_model(), id=media_id)

    return render_modal_workflow(
        request,
        None,
        None,
        None,
        json_data={"step": "media_chosen", "result": get_media_json(media)},
    )


@permission_checker.require("add")
def chooser_upload(request, media_type):
    Media = get_media_model()
    MediaForm = get_media_form(Media)

    if request.method == "POST":
        media = Media(uploaded_by_user=request.user, type=media_type)
        form = MediaForm(
            request.POST,
            request.FILES,
            instance=media,
            user=request.user,
            prefix="media-chooser-upload",
        )
        if form.is_valid():
            form.save()

            # Reindex the media entry to make sure all tags are indexed
            for backend in get_search_backends():
                backend.add(media)

            return render_modal_workflow(
                request,
                None,
                None,
                None,
                json_data={"step": "media_chosen", "result": get_media_json(media)},
            )

    media_files = permission_policy.instances_user_has_any_permission_for(
        request.user, ["change", "delete"]
    )

    # allow hooks to modify the queryset
    for hook in hooks.get_hooks("construct_media_chooser_queryset"):
        media_files = hook(media_files, request)

    searchform = SearchForm()

    collections = Collection.objects.all()
    if len(collections) < 2:
        collections = None

    media_files = media_files.order_by("-created_at")
    paginator, media_files = paginate(request, media_files, per_page=10)

    context = {
        "media_files": media_files,
        "searchform": searchform,
        "collections": collections,
        "uploadform": form,
        "is_searching": False,
        "pagination_template": pagination_template,
        "media_type": media_type,
    }
    return render_modal_workflow(
        request,
        "wagtailmedia/chooser/chooser.html",
        None,
        context,
        json_data={"step": "chooser"},
    )

wagtailmedia/templates/wagtailmedia/media/_file_field.html
{% extends "wagtailadmin/shared/field.html" %}
{% load i18n %}
{% block form_field %}
    <a href="{{ media.url }}" class="icon icon-media">{{ media.filename }}</a><br /><br />
    {% trans "Change media file:" %}
    {{ field }}
{% endblock %}

wagtailmedia/templates/wagtailmedia/media/_file_field_as_li.html
{% load wagtailadmin_tags %}
<li class="{% if field.field.required %}required{% endif %} {{ wrapper_classes }} {{ li_classes }} {% if field.errors %}error{% endif %}">
    {% include "wagtailmedia/media/_file_field.html" %}
</li>

wagtailmedia/templates/wagtailmedia/media/_thumbnail_field.html
{% extends "wagtailadmin/shared/field.html" %}
{% load i18n %}
{% block form_field %}

    {% if media.thumbnail %}
        <a href="{{ media.thumbnail.url }}" class="icon icon-image">{{ media.thumbnail_filename }}</a><br /><br />
    {% endif %}

    {% trans "Change thumbnail file:" %}
    {{ field }}
{% endblock %}

wagtailmedia/templates/wagtailmedia/media/_thumbnail_field_as_li.html
{% load wagtailadmin_tags %}
<li class="{% if field.field.required %}required{% endif %} {{ wrapper_classes }} {{ li_classes }} {% if field.errors %}error{% endif %}">
    {% include "wagtailmedia/media/_thumbnail_field.html" %}
</li>

wagtailmedia/templates/wagtailmedia/media/add.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% load wagtailimages_tags %}
{% block titletag %}
    {% if media_type == 'audio' %}
        {% trans "Add audio" %}
    {% elif media_type == 'video' %}
        {% trans "Add video" %}
    {% else %}
        {% trans "Add audio or video" %}
    {% endif %}
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    {{ form.media.js }}

    {% url 'wagtailadmin_tag_autocomplete' as autocomplete_url %}
    <script>
        $(function() {
            $('#id_tags').tagit({
                autocomplete: {source: "{{ autocomplete_url|addslashes }}"}
            });
        });
    </script>
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock %}

{% block content %}
    {% if media_type == 'audio' %}
        {% trans "Add audio" as add_str %}
    {% elif media_type == 'video' %}
        {% trans "Add video" as add_str %}
    {% else %}
        {% trans "Add audio or video" as add_str %}
    {% endif %}
    {% include "wagtailadmin/shared/header.html" with title=add_str icon="media" %}

    <div class="nice-padding">
        <form action="{% block action %}{% url 'wagtailmedia:add' media_type %}{% endblock %}" method="POST" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            <ul class="fields">
                {% for field in form %}
                    {% include "wagtailadmin/shared/field_as_li.html" with field=field %}
                {% endfor %}
                <li>
                    <button type="submit" class="button button-longrunning" data-clicked-text="{% trans 'Uploading…' %}"><span class="icon icon-spinner"></span><em>{% trans 'Upload' %}</em></button>
                </li>
            </ul>
        </form>
    </div>
{% endblock %}

wagtailmedia/templates/wagtailmedia/media/confirm_delete.html
{% extends "wagtailadmin/base.html" %}
{% load wagtailadmin_tags i18n %}
{% block titletag %}{% blocktrans with title=media.title %}Delete {{ title }}{% endblocktrans %}{% endblock %}
{% block content %}
    {% trans "Delete media file" as del_str %}
    {% include "wagtailadmin/shared/header.html" with title=del_str subtitle=media.title icon="media" %}

    <div class="nice-padding">
        {% usage_count_enabled as uc_enabled %}
        {% if uc_enabled %}
            <div class="usagecount">
                <a href="{{ media.usage_url }}">{% blocktrans count usage_count=media.get_usage.count %}Used {{ usage_count }} time{% plural %}Used {{ usage_count }} times{% endblocktrans %}</a>
            </div>
        {% endif %}

        <p>{% trans "Are you sure you want to delete this media file?" %}</p>
        <form action="{% url 'wagtailmedia:delete' media.id %}" method="POST" novalidate>
            {% csrf_token %}
            <input type="submit" value='{% trans "Yes, delete" %}' class="button serious" />
        </form>
    </div>
{% endblock %}

wagtailmedia/templates/wagtailmedia/media/edit.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% load wagtailimages_tags wagtailadmin_tags %}
{% block titletag %}{% blocktrans with title=media.title %}Editing {{ title }}{% endblocktrans %}{% endblock %}

{% block extra_js %}
    {{ block.super }}
    {{ form.media.js }}

    {% url 'wagtailadmin_tag_autocomplete' as autocomplete_url %}
    <script>
        $(function() {
            $('#id_tags').tagit({
                autocomplete: {source: "{{ autocomplete_url|addslashes }}"}
            });
        });
    </script>
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock %}

{% block content %}
    {% trans "Editing" as editing_str %}
    {% include "wagtailadmin/shared/header.html" with title=editing_str subtitle=media.title icon="media" usage_object=media %}

    {% block form_row %}
        <div class="row row-flush nice-padding">

            <div class="col10 divider-after">
                <form action="{% url 'wagtailmedia:edit' media.id %}" method="POST" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    <ul class="fields">
                        {% for field in form %}
                            {% if field.name == 'file' %}
                                {% include "wagtailmedia/media/_file_field_as_li.html" %}
                            {% elif field.name == 'thumbnail' %}
                                {% include "wagtailmedia/media/_thumbnail_field_as_li.html" %}
                            {% else %}
                                {% include "wagtailadmin/shared/field_as_li.html" %}
                            {% endif %}
                        {% endfor %}
                        <li>
                            <input class="button" type="submit" value="{% trans 'Save' %}" />
                            {% if user_can_delete %}
                                <a href="{% url 'wagtailmedia:delete' media.id %}" class="button button-secondary no">{% trans "Delete" %}</a>
                            {% endif %}
                        </li>
                    </ul>
                </form>
            </div>
            <div class="col2">
                <dl>
                    {% block media_stats %}
                        {% if media.file %}
                            <dt>{% trans "Filesize" %}</dt>
                            <dd>{% if filesize %}{{ filesize|filesizeformat }}{% else %}{% trans "File not found" %}{% endif %}</dd>
                        {% endif %}

                        {% usage_count_enabled as uc_enabled %}
                        {% if uc_enabled %}
                            <dt>{% trans "Usage" %}</dt>
                            <dd>
                                <a href="{{ media.usage_url }}">{% blocktrans count usage_count=media.get_usage.count %}Used {{ usage_count }} time{% plural %}Used {{ usage_count }} times{% endblocktrans %}</a>
                            </dd>
                        {% endif %}
                    {% endblock %}
                </dl>
            </div>
        </div>
    {% endblock %}

    </div>
{% endblock %}

wagtailmedia/templates/wagtailmedia/media/index.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}Media{% endblock %}
{% block extra_js %}
    {{ block.super }}
    <script>
        window.headerSearch = {
            url: "{% url 'wagtailmedia:index' %}",
            termInput: "#id_q",
            targetOutput: "#media-results"
        };

        $(function() {
            $('#collection_chooser_collection_id').change(function() {
                this.form.submit();
            })
        });
    </script>
{% endblock %}

{% block content %}
    {% trans "Media" as media_str %}
    <header class="nice-padding">
        <div class="row">
            <div class="left">
                <div class="col">
                    <h1 class="icon icon-media">
                    {{ media_str }}
                    </h1>
                </div>
                <form class="col search-form" action="{% url 'wagtailmedia:index' %}{% if query_parameters %}?{{ query_parameters }}{% endif %}" method="get" novalidate>
                    <ul class="fields">
                        {% for field in search_form %}
                            {% include "wagtailadmin/shared/field_as_li.html" with field=field field_classes="field-small iconfield" input_classes="icon-search" %}
                        {% endfor %}
                        <li class="submit visuallyhidden"><input type="submit" value="Search" class="button" /></li>
                    </ul>
                </form>
            </div>
            {% if user_can_add %}
                {% block add_actions %}
                    <div class="right">
                        <div class="addbutton">
                            <a href="{% url 'wagtailmedia:add' 'audio' %}" class="button bicolor icon icon-plus">{% trans "Add audio" %}</a>
                        </div>
                    </div>
                    <div class="right">
                        <div class="col">
                            <div class="addbutton">
                                <a href="{% url 'wagtailmedia:add' 'video' %}" class="button bicolor icon icon-plus">{% trans "Add video" %}</a>
                            </div>
                        </div>
                    </div>
                {% endblock %}
            {% endif %}
        </div>
    </header>

    <div class="nice-padding">
        {% if collections %}
            <form class="image-search search-bar" action="{% url 'wagtailmedia:index' %}" method="GET" novalidate>
                <ul class="fields">
                    {% include "wagtailadmin/shared/collection_chooser.html" %}
                </ul>
            </form>
        {% endif %}

        <div id="media-results" class="media">
            {% include "wagtailmedia/media/results.html" %}
        </div>
    </div>
{% endblock %}

wagtailmedia/templates/wagtailmedia/media/list.html
{% load i18n %}
<table class="listing">
    <col />
    <col  />
    <col width="16%" />
    <thead>
        <tr class="table-headers">
            <th>
                {% if not is_searching %}
                    <a href="{% url 'wagtailmedia:index' %}{% if not ordering == "title" %}?ordering=title{% endif %}" class="icon icon-arrow-down-after {% if  ordering == "title" %}teal{% endif %}">
                        {% trans "Title" %}
                    </a>
                {% else %}
                    {% trans "Title" %}
                {% endif %}
            </th>
            <th>{% trans "File" %}</th>
            <th>{% trans "Type" %}</th>
            <th>
                {% if not is_searching %}
                    <a href="{% url 'wagtailmedia:index' %}{% if not ordering == "-created_at" %}?ordering=-created_at{% endif %}" class="icon icon-arrow-down-after {% if  ordering == "-created_at" %}teal{% endif %}">
                        {% trans "Uploaded" %}
                    </a>
                {% else %}
                    {% trans "Uploaded" %}
                {% endif %}
            </th>
        </tr>
    </thead>
    <tbody>
        {% for media_file in media_files %}
            <tr>
                <td class="title">
                    {% if choosing %}
                        <h2><a href="{% url 'wagtailmedia:media_chosen' media_file.id %}" class="media-choice">{{ media_file.title }}</a></h2>
                    {% else %}
                        <h2><a href="{% url 'wagtailmedia:edit' media_file.id %}">{{ media_file.title }}</a></h2>
                    {% endif %}
                </td>
                <td>
                    {% if choosing %}
                        {{ media_file.filename }}
                    {% else %}
                        <a href="{{ media_file.url }}" class="nolink">{{ media_file.filename }}</a>
                    {% endif %}
                </td>
                <td>{{ media_file.get_type_display }}</td>
                <td><div class="human-readable-date" title="{{ media_file.created_at|date:"d M Y H:i" }}">{{ media_file.created_at|timesince }} ago</div></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

wagtailmedia/templates/wagtailmedia/media/results.html
{% load i18n wagtailadmin_tags %}
{% if media_files %}
    {% if is_searching %}
        <h2>
        {% blocktrans count counter=media_files|length %}
            There is one match
        {% plural %}
            There are {{ counter }} matches
        {% endblocktrans %}
        </h2>

        {% search_other %}
    {% endif %}

    {% include "wagtailmedia/media/list.html" %}

    {% include "wagtailadmin/shared/pagination_nav.html" with items=media_files is_searching=is_searching linkurl="wagtailmedia:index" %}
{% else %}
    {% if is_searching %}
         <h2>{% blocktrans %}Sorry, no media files match "<em>{{ query_string }}</em>"{% endblocktrans %}</h2>

         {% search_other %}
    {% else %}
        {% url 'wagtailmedia:add' 'audio' as wagtailmedia_add_audio_url %}
        {% url 'wagtailmedia:add' 'video' as wagtailmedia_add_video_url %}
        {% if current_collection %}
            <p>{% blocktrans %}You haven't uploaded any media files in this collection. You can upload <a href="{{ wagtailmedia_add_audio_url }}">audio</a> or <a href="{{ wagtailmedia_add_video_url }}">video</a> files.{% endblocktrans %}</p>
        {% else %}
            <p>{% blocktrans %}You haven't uploaded any media files. You can upload <a href="{{ wagtailmedia_add_audio_url }}">audio</a> or <a href="{{ wagtailmedia_add_video_url }}">video</a> files.{% endblocktrans %}</p>
        {% endif %}
    {% endif %}
{% endif %}

wagtailmedia/templates/wagtailmedia/media/usage.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with title=media.title %}Usage of {{ title }}{% endblocktrans %}{% endblock %}
{% block content %}
    {% trans "Usage of" as usage_str %}
    {% include "wagtailadmin/shared/header.html" with title=usage_str subtitle=media.title %}

    <div class="nice-padding">
        <table class="listing">
            <col />
            <col width="30%"/>
            <col width="15%"/>
            <col width="15%"/>
            <thead>
                <tr>
                    <th class="title">{% trans "Title" %}</th>
                    <th>{% trans "Parent" %}</th>
                    <th>{% trans "Type" %}</th>
                    <th>{% trans "Status" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for page in used_by %}
                    <tr>
                        <td class="title" valign="top">
                            <h2><a href="{% url 'wagtailadmin_pages:edit' page.id %}" title="{% trans 'Edit this page' %}">{{ page.title }}</a></h2>
                        </td>
                        <td>
                            {% if page.get_parent %}
                                <a href="{% url 'wagtailadmin_explore' page.get_parent.id %}">{{ page.get_parent.title }}</a>
                            {% endif %}
                        </td>
                        <td>
                            {{ page.content_type.model_class.get_verbose_name }}
                        </td>
                        <td>
                            {% include "wagtailadmin/shared/page_status_tag.html" with page=page %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% include "wagtailadmin/shared/pagination_nav.html" with items=used_by linkurl="-" %}
{% endblock %}